#ifndef BASE_SCHEME_VALUE_TEST_H
#define BASE_SCHEME_VALUE_TEST_H
#pragma once

#include "paper-scheme/runtime.h"

/**
 * 值类型测试
 * 测试基础类型是否工作正常
 */

UTEST(value_test, all_type_function_test) {
    context_t context = context_make(0x100, 2, 0x100000);
    gc_collect_disable(context);
    object obj = NULL;

    object null_object = NULL;
    obj = null_object;
    ASSERT_TRUE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object imm_true = IMM_TRUE;
    obj = imm_true;
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_TRUE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object imm_false = IMM_FALSE;
    obj = imm_false;
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_TRUE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object imm_unit = IMM_UNIT;
    obj = imm_unit;
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_TRUE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object imm_char = char_imm_make('x');
    obj = imm_char;
    ASSERT_EQ('x', char_imm_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_TRUE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    imm_char = char_imm_make('\0');
    obj = imm_char;
    ASSERT_EQ('\0', char_imm_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_TRUE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object imm_i64 = i64_imm_make(123);
    obj = imm_i64;
    ASSERT_EQ(123, i64_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_TRUE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_TRUE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_FALSE(is_object(obj));
    ASSERT_TRUE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object i64 = i64_make_real_object_op(context, 20);
    obj = i64;
    ASSERT_EQ(20, i64_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_TRUE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_TRUE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    i64 = i64_make_op(context, INT64_MAX);
    obj = i64;
    ASSERT_EQ(INT64_MAX, i64_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_TRUE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_TRUE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    i64 = i64_make_real_object_op(context, INT64_MIN);
    obj = i64;
    ASSERT_EQ(INT64_MIN, i64_getvalue(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_TRUE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_TRUE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object doublenum = doublenum_make_op(context, 200.0);
    obj = doublenum;
    ASSERT_EQ(doublenum_getvalue(obj), 200.0);
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_TRUE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object pair_carImmI64_cdrDouble = pair_make_op(context, imm_i64, doublenum);
    obj = pair_carImmI64_cdrDouble;
    ASSERT_EQ(pair_car(obj), imm_i64);
    ASSERT_EQ(i64_getvalue(pair_car(obj)), i64_getvalue(imm_i64));
    ASSERT_EQ(doublenum_getvalue(pair_cdr(obj)), doublenum_getvalue(doublenum));
    ASSERT_EQ(pair_cdr(obj), doublenum);
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_TRUE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    char str[] = "this is a string object";
    object string_obj = string_make_from_cstr_op(context, str);
    obj = string_obj;
    ASSERT_EQ(strlen(str), string_len(obj));
    for (size_t i = 0; i < strlen(str); i++) {
        ASSERT_EQ(str[i], string_index(obj, i));
    }
    for (size_t i = 0; i < strlen(str); i++) {
        ASSERT_EQ(str[i], string_get_cstr(obj)[i]);
    }
    ASSERT_EQ(string_index(obj, string_len(obj)), '\0');
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_TRUE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object string_null_object = string_make_from_cstr_op(context, NULL);
    obj = string_null_object;
    ASSERT_EQ(0, string_len(obj));
    ASSERT_EQ('\0', string_index(obj, 0));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_TRUE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object string_empty = string_make_from_cstr_op(context, "");
    obj = string_empty;
    ASSERT_EQ(0, string_len(obj));
    ASSERT_EQ('\0', string_index(obj, 0));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_TRUE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    char symbol_str[] = "this is a symbol object";
    object symbol_obj = symbol_make_from_cstr_op(context, symbol_str);
    obj = symbol_obj;
    ASSERT_EQ(strlen(str), symbol_len(obj));
    for (size_t i = 0; i <= strlen(symbol_str); i++) {
        ASSERT_EQ(symbol_str[i], symbol_index(obj, i));
    }
    for (size_t i = 0; i <= strlen(symbol_str); i++) {
        ASSERT_EQ(symbol_str[i], symbol_get_cstr(obj)[i]);
    }
    ASSERT_EQ(symbol_index(obj, symbol_len(obj)), '\0');
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_TRUE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object symbol_null_object = symbol_make_from_cstr_op(context, NULL);
    obj = symbol_null_object;
    ASSERT_EQ(0, symbol_len(obj));
    ASSERT_EQ('\0', symbol_index(obj, 0));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_TRUE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object symbol_empty = symbol_make_from_cstr_op(context, "");
    obj = symbol_empty;
    ASSERT_EQ(0, symbol_len(obj));
    ASSERT_EQ('\0', symbol_index(obj, 0));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_TRUE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object vector10 = vector_make_op(context, 10);
    obj = vector10;
    for (size_t i = 0; i < vector_len(obj); i++) {
        ASSERT_EQ(IMM_UNIT, vector_ref(obj, i));
    }
    vector_ref(obj, 1) = imm_i64;
    ASSERT_EQ(vector_ref(obj, 1), imm_i64);
    ASSERT_EQ(10, vector_len(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_TRUE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object vector20 = vector_make_op(context, 20);
    obj = vector20;
    for (size_t i = 0; i < vector_len(obj); i++) {
        ASSERT_EQ(IMM_UNIT, vector_ref(obj, i));
    }
    ASSERT_EQ(20, vector_len(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_TRUE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object vector0 = vector_make_op(context, 0);
    obj = vector0;
    for (size_t i = 0; i < vector_len(obj); i++) {
        ASSERT_EQ(IMM_UNIT, vector_ref(obj, i));
    }
    ASSERT_EQ(0, vector_len(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_TRUE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object bytes = bytes_make_op(context, 10);
    obj = bytes;
    for (size_t i = 0; bytes_capacity(obj) > i; i++) {
        ASSERT_EQ(bytes_index(obj, i), 0);
    }
    bytes_index(obj, 0) = 2;
    ASSERT_EQ(bytes_data(obj), obj->value.bytes.data);
    ASSERT_EQ(obj->value.bytes.data[0], bytes_index(obj, 0));
    ASSERT_EQ(2, bytes_index(obj, 0));
    ASSERT_EQ(10, bytes_capacity(obj));
    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_TRUE(is_bytes(obj));
    ASSERT_FALSE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    object string_buffer = string_buffer_make_op(context, STRING_BUFFER_DEFAULT_INIT_SIZE);
    obj = string_buffer;
    ASSERT_TRUE(string_buffer_empty(obj));

    ASSERT_FALSE(is_null(obj));
    ASSERT_FALSE(is_imm(obj));
    ASSERT_FALSE(is_unique_imm(obj));
    ASSERT_FALSE(is_i64_real(obj));
    ASSERT_FALSE(is_imm_i64(obj));
    ASSERT_FALSE(is_imm_char(obj));
    ASSERT_TRUE(is_object(obj));
    ASSERT_FALSE(is_i64(obj));
    ASSERT_FALSE(is_doublenum(obj));
    ASSERT_FALSE(is_pair(obj));
    ASSERT_FALSE(is_string(obj));
    ASSERT_FALSE(is_symbol(obj));
    ASSERT_FALSE(is_vector(obj));
    ASSERT_FALSE(is_bytes(obj));
    ASSERT_TRUE(is_string_buffer(obj));
    ASSERT_FALSE(is_stack(obj));
    ASSERT_FALSE(is_string_port(obj));
    ASSERT_FALSE(is_string_port_input(obj));
    ASSERT_FALSE(is_string_port_output(obj));
    ASSERT_FALSE(is_string_port_in_out_put(obj));
    ASSERT_FALSE(is_string_port_eof(obj));
    ASSERT_FALSE(is_stdio_port(obj));
    ASSERT_FALSE(is_stdio_port_input(obj));
    ASSERT_FALSE(is_stdio_port_output(obj));
    ASSERT_FALSE(is_stdio_port_in_out_put(obj));
    ASSERT_FALSE(is_stdio_port_eof(obj));
    ASSERT_FALSE(is_port_input(obj));
    ASSERT_FALSE(is_port_output(obj));
    ASSERT_FALSE(is_port_in_out_put(obj));
    ASSERT_FALSE(is_port_eof(obj));
    ASSERT_FALSE(is_srfi6_port(obj));

    gc_collect_enable(context);
    int64_t start = utest_ns();
    gc_collect(context);
    int64_t time = utest_ns() - start;
    UTEST_PRINTF("gc time: %"
                         PRId64
                         " ns\n", time);
    ASSERT_TRUE(context->heap->first_node->data == context->heap->first_node->free_ptr);
    context_destroy(context);
}

#endif //BASE_SCHEME_VALUE_TEST_H
